---
title: "Immune Response Predictor"
output: html_document
params:
  study: "SDY269"
  cohorts_train: "LAIV group 2008_PBMC"
  cohorts_test: "TIV Group 2008_PBMC"
  timepoint: 7
  timepoint_unit: "Days"
  assay: "hai" 
  use_only_de_genes: TRUE
  fc_thresh: 0.5
  dichotomize: FALSE
  dichotomize_thresh: 4
---

```{r setup, echo = FALSE}
suppressPackageStartupMessages({
  library(HIPCMatrix)
  library(ImmuneSpaceR)
  library(knitr)
  library(ggplot2)
  library(plotly)
  library(data.table)
  library(DT)
})

opts_chunk$set(cache = FALSE,
               echo = FALSE,
               message = FALSE,
               warning = FALSE,
               fig.width = 12,
               fig.height = 10,
               fig.align = "center")
```


```{r train}
con <- HMX$new(params$study)
model <- con$train_immune_response_predictors(
  cohorts = params$cohorts_train,
  timepoint = params$timepoint, 
  assay = params$assay, 
  timepoint_unit = params$timepoint_unit, 
  use_only_de_genes = params$use_only_de_genes, 
  fc_thresh = params$fc_thresh, 
  dichotomize = params$dichotomize, 
  dichotomize_thresh = params$dichotomize_thresh
)
```

## Predicted response vs. observed response per Participant
```{r prediction, echo=FALSE, dev='CairoPNG'}

data_train <- con$test_immune_response_predictors(
  cohorts = params$cohorts_train, 
  timepoint = params$timepoint, 
  fit = model, 
  assay = params$assay, 
  timepoint_unit = params$timepoint_unit, 
  dichotomize = params$dichotomize, 
  dichotomize_thresh = params$dichotomize_thresh
)

if ( length(params$cohorts_test) == 0 ) {
  
  p <- ggplot(data_train, aes(x = observed, y = predicted)) + 
    geom_point() + 
    geom_smooth(method = "lm") + 
    theme_IS()
  
} else {
  
  data_test <- con$test_immune_response_predictors(
    cohorts = params$cohorts_test, 
    timepoint = params$timepoint, 
    fit = model, 
    assay = params$assay, 
    timepoint_unit = params$timepoint_unit, 
    dichotomize = params$dichotomize, 
    dichotomize_thresh = params$dichotomize_thresh
  )
  data_train[, cohort_label := paste0(params$cohorts_train, " (Training)")]
  data_test[, cohort_label := paste0(params$cohorts_test, " (Testing)")]
  data <- rbind( data_test, data_train)
  
  p <- ggplot(data, aes(x = observed, y = predicted)) + 
    geom_point() + 
    geom_smooth(method = "lm") +
    facet_wrap(~cohort_label, scale="free") + 
    xlab("Observed HAI response") + 
    ylab("Predicted HAI response") + 
    theme_IS()
}
#plot(p)
ggplotly(p)
```


## Heatmap of selected features
```{r heatmap, echo = FALSE, cache = FALSE}
eset <- con$getGEMatrix(cohortType = c(params$cohorts_train, params$cohorts_test))
mat <- t(HIPCMatrix:::get_fc_mx(
  eset = eset, 
  timepoint = params$timepoint,
  features = names(model$coefficients)[2:length(model$coefficients)]))

pd <- data.table(Biobase::pData(eset))
response <- con$get_immune_response(
  assay = params$assay, 
  dichotomize = params$dichotomize, 
  participant_ids = unique(colnames(mat)),
  dichotomize_thresh = params$dichotomize_thresh, 
)
anno <- merge(response, pd, all.x = TRUE, all.y = FALSE)
anno[, set := ifelse(cohort_type %in% params$cohorts_train,
                            "Training", 
                            "Testing")]
setorder(anno, -set, cohort_type, response)

anno <- unique(anno[participant_id %in% colnames(mat), 
             .(participant_id, 
               response,cohort_type, 
               set)])
anno <- data.frame(anno[, -"participant_id"], row.names = anno$participant_id)

if ( params$dichotomize ) {
  anno$response <- as.factor(anno$response)
  anno_col <- list(response = c(`FALSE` = "white", `TRUE` = "black"))
} else {
  anno_col <- list(response = grey(seq(1, 0, by = -.1)))
}

mat <- mat[, rownames(anno)]
mat2 <- mat
rownames(mat) <- ifelse(nchar(rownames(mat)) > 15, paste0(substr(rownames(mat), 1, 15), "..."), rownames(mat))
pheatmap::pheatmap(mat,
        annotation = anno,
        annotation_colors = anno_col,
        scale = "row",
        color = ISpalette(20),
        cluster_rows = TRUE,
        cluster_distance = "correlation",
        cluster_method = "ward",
        dendrogram = "none",
        cluster_cols = FALSE,
        show_colnames = FALSE)
# heatmaply(x = mat2,
#           dendrogram = "row",
#           scale = "row",
#           distfun = function(x) as.dist(1 - cor(t(x))),
#           hclust_method = "ward.D",
#           colors = ISpalette(20),
#           col_side_colors = anno)
```



## Table of genes selected by the elastic net
```{r kable}
datatable(format_predictor_table(model), escape = 1, width = 600)
```


